### ISSUE TITLE
forme_set exlude a column

### ISSUE THREAD

**Issue by pjaspers** [jeremyevans/forme#117] opened 2023-10-12 20:59 UTC
I have a form that has a file upload field:

``` ruby
form(@thing) do |f|
  f.input(:attached_file)
end
```

Is there a way I can convince `forme_set` to not set this column if the value is empty? So that it only gets set if a file was attached. It seems like `forme_set` will look at the columns, and then set it to nil because no file was attached. (I'm also doing a `r.params[:thing][:attached_file] = Sequel.blob(r.params[:thing][:attached_file]` because I couldn't find a way to transform the input before hand)

**Comment by jeremyevans** [comment] 2023-10-12 21:09
You can use `forme_parse` instead of `forme_set` if you want to customize the setting of the parameters.  `forme_set` just takes the values provided by `forme_parse` and passes them to `set`.

I'm going to close this now as this is not a bug in Forme.  You can continue discussion here if you would like.  However, for future questions regarding Forme that are not bug reports, please open a Discussion instead of an Issue.

**Closed by jeremyevans** 2023-10-12 21:09 UTC
